services:
  be:
    build: ./LIDM-BE
    ports:
      - "8000:80"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      DB_CONNECTION: sqlite

  fe:
    build:
      context: ./LIDM-FE
      target: dev
    volumes:
      - ./LIDM-FE:/app
      - fe_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - be

volumes:
  fe_node_modules:
